### ISSUE TITLE
关于laya

### ISSUE THREAD

**Issue by jweiBase** [yanmingjie0223/Laya#1]
你好。根据你工程设计的思路，请问那个使用编辑界面编辑的怎么调用？你那个laya的工程设计思路有没有教学视频参考？谢谢。

**Comment by yanmingjie0223** [comment]
这个设计思路主要在于control控制view、数据交互。编辑器编辑的界面可以再BaseView初始化界面时候将编辑的界面new出来添加到BaseView中。个人比较习惯用代码写，UI编辑界面问题还是比较多的
